#===========================================#
#{ONLINE} - Shows the number of players online
#{MAXONLINE} - Show the number of max player online
#{PLAYERNAME} - Shows player's name
#{MOTE} - Show server motd
#{IP} - Show Server ip
#{PORT} - Show server port
#{VERSION} - Show server version
#===========================================#
LINE1: "Welcome back, {PLAYERNAME} !"
LINE2: "There are {ONLINE}/{MAXONLINE} Players online!"
LINE3: "{IP}:{PORT}"
LINE4: "{VERSION}"
LINE5: "hello"
LINE6: "There"

#Cordinates
# you can find your Cordinates by doing /cords in game

#first text
Xs: 273
Ys: 67
Zs: 197
